# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-02 16:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='PadAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorID', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'verbose_name': 'author',
            },
        ),
        migrations.CreateModel(
            name='PadGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupID', models.CharField(blank=True, max_length=256)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
            options={
                'verbose_name': 'group',
            },
        ),
        migrations.CreateModel(
            name='PadServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('url', models.URLField(max_length=256, verbose_name='URL')),
                ('apikey', models.CharField(max_length=256, verbose_name='API key')),
                ('notes', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'server',
            },
        ),
        migrations.AddField(
            model_name='padgroup',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etherpadlite.PadServer'),
        ),
        migrations.AddField(
            model_name='padauthor',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, related_name='authors', to='etherpadlite.PadGroup'),
        ),
        migrations.AddField(
            model_name='padauthor',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etherpadlite.PadServer'),
        ),
        migrations.AddField(
            model_name='padauthor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pad',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etherpadlite.PadGroup'),
        ),
        migrations.AddField(
            model_name='pad',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etherpadlite.PadServer'),
        ),
    ]
