# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-02 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etherpadlite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padauthor',
            name='group',
            field=models.ManyToManyField(blank=True, related_name='authors', to='etherpadlite.PadGroup'),
        ),
    ]
